# Generated by Django 4.2.7 on 2023-11-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Bill_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
