# Generated by Django 4.2.7 on 2023-12-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0005_remove_boss_bonus_boss_email_boss_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='Unit',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='Amount',
            field=models.FloatField(null=True),
        ),
    ]
