# Generated by Django 4.2.7 on 2023-12-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0006_ingredient_unit_alter_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='Unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
