# Generated by Django 4.2.7 on 2023-12-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0009_alter_ingredient_amount_alter_ingredient_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
