# Generated by Django 4.2.7 on 2023-12-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0012_remove_dish_orderid_remove_dish_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='Cashier_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
