# Generated by Django 4.2.7 on 2023-12-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0013_alter_cashier_cashier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
