# Generated by Django 4.2.7 on 2023-12-06 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0017_boss_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='menu',
        ),
        migrations.AddField(
            model_name='category',
            name='Description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='MenuID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplication.menu'),
        ),
    ]
