# Generated by Django 4.2.7 on 2023-12-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0018_remove_category_menu_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='MenuID',
            new_name='menu',
        ),
    ]
