# Generated by Django 4.2.7 on 2023-12-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0019_rename_menuid_category_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='CategoryID',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='RecipeID',
        ),
    ]
