# Generated by Django 4.2.7 on 2023-12-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0022_remove_bill_amount_remove_bill_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='RestaurantID',
        ),
    ]
