# Generated by Django 4.2.7 on 2023-12-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0023_remove_employees_restaurantid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ContcNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Sex',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
