# Generated by Django 4.2.7 on 2023-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0024_alter_customer_contcnumber_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='Transaction_Date',
            field=models.DateField(null=True),
        ),
    ]
